---

- name: Install zypper on Ubuntu
  apt:
    name: zypper
    state: present

- name: Add OpenStack Ussuri repository on Ubuntu
  command: >
    sudo zypper addrepo -f obs://Cloud:OpenStack:Ussuri/openSUSE_Leap_15.1 Ussuri

- name: Install Openstack Python client on Ubuntu
  command: >
    sudo apt install python3-openstackclient

- name: Install Glance on server2 (Ubuntu)
  when: ansible_distribution == "Ubuntu"
  apt:
    name: glance
    state: present

