---

- hosts: all
  become: true
  pre_tasks:

  - name: Install Updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install Updates (CentOS)
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: server1
  become: true
  roles:
    - Keystone

- hosts: server2
  become: true
  roles:
    - Glance

- hosts: server3
  become: true
  roles:
    - Nova
